import axios from "axios";

// TODO: Extract survey answers from data object
function UploadFirst1To7(input) {
  let url = "http://localhost:3001/create";
  let data = {
    record_id: input.record_id,
    question_1: "question_1",
    question_2: "question_2",
    question_3: "question_3",
    question_4: "question_4",
    question_5: "question_5",
    question_6: "question_6",
    question_7: "question_7",
    question_8: "",
    question_9: "",
    question_10: "",
    question_11: "",
    question_12: "",
    question_13: "",
    question_14: "",
    question_15: "",
    question_16: "",
    question_17: "",
    question_18: "",
    question_19: "",
    question_20: "",
    question_21: "",
    question_22: "",
    question_23: "",
    question_24: "",
    question_25: "",
    question_26: "",
    question_27: "",
    question_28: "",
    question_29: "",
    question_30: "",
    question_31: "",
    question_32: "",
    question_33: "",
    question_34: "",
    question_35: "",
    question_36: "",
    question_37: "",
    question_38: "",
    question_39: "",
    question_40: "",
    question_41: "",
    question_42: "",
    question_43: "",
    question_44: "",
    question_45: "",
    question_46: "",
    question_47: "",
    question_48: "",
    question_49: "",
    question_50: "",
    question_51: "",
    question_52: "",
    question_53: "",
    question_54: "",
    question_55: "",
    question_56: "",
    question_57: "",
    question_58: "",
    answers_complete: 0,
  };

  console.log("UploadFirst1To7 - RESPONSE:");
  AxiosCall(url, data);
}

function UploadSecond8To26(input) {
  let url = "http://localhost:3001/update";
  let data = {
    record_id: input.record_id,
    question_1: "",
    question_2: "",
    question_3: "",
    question_4: "",
    question_5: "",
    question_6: "",
    question_7: "",
    question_8: "question_8",
    question_9: "question_9",
    question_10: "question_10",
    question_11: "question_11",
    question_12: "question_12",
    question_13: "question_13",
    question_14: "question_14",
    question_15: "question_15",
    question_16: "question_16",
    question_17: "question_17",
    question_18: "question_18",
    question_19: "question_19",
    question_20: "question_20",
    question_21: "question_21",
    question_22: "question_22",
    question_23: "question_23",
    question_24: "question_24",
    question_25: "question_25",
    question_26: "question_26",
    question_27: "",
    question_28: "",
    question_29: "",
    question_30: "",
    question_31: "",
    question_32: "",
    question_33: "",
    question_34: "",
    question_35: "",
    question_36: "",
    question_37: "",
    question_38: "",
    question_39: "",
    question_40: "",
    question_41: "",
    question_42: "",
    question_43: "",
    question_44: "",
    question_45: "",
    question_46: "",
    question_47: "",
    question_48: "",
    question_49: "",
    question_50: "",
    question_51: "",
    question_52: "",
    question_53: "",
    question_54: "",
    question_55: "",
    question_56: "",
    question_57: "",
    question_58: "",
    answers_complete: 0,
  };

  console.log("UploadSecond8To26 - RESPONSE:");
  AxiosCall(url, data);
}

function UploadThird27To34(input) {
  let url = "http://localhost:3001/update";
  let data = {
    record_id: input.record_id,
    question_1: "",
    question_2: "",
    question_3: "",
    question_4: "",
    question_5: "",
    question_6: "",
    question_7: "",
    question_8: "",
    question_9: "",
    question_10: "",
    question_11: "",
    question_12: "",
    question_13: "",
    question_14: "",
    question_15: "",
    question_16: "",
    question_17: "",
    question_18: "",
    question_19: "",
    question_20: "",
    question_21: "",
    question_22: "",
    question_23: "",
    question_24: "",
    question_25: "",
    question_26: "",
    question_27: "question_27",
    question_28: "question_28",
    question_29: "question_29",
    question_30: "question_30",
    question_31: "question_31",
    question_32: "question_32",
    question_33: "question_33",
    question_34: "question_34",
    question_35: "",
    question_36: "",
    question_37: "",
    question_38: "",
    question_39: "",
    question_40: "",
    question_41: "",
    question_42: "",
    question_43: "",
    question_44: "",
    question_45: "",
    question_46: "",
    question_47: "",
    question_48: "",
    question_49: "",
    question_50: "",
    question_51: "",
    question_52: "",
    question_53: "",
    question_54: "",
    question_55: "",
    question_56: "",
    question_57: "",
    question_58: "",
    answers_complete: 0,
  };

  console.log("UploadThird27To34 - RESPONSE:");
  AxiosCall(url, data);
}

function UploadFourth35To49(input) {
  let url = "http://localhost:3001/update";
  let data = {
    record_id: input.record_id,
    question_1: "",
    question_2: "",
    question_3: "",
    question_4: "",
    question_5: "",
    question_6: "",
    question_7: "",
    question_8: "",
    question_9: "",
    question_10: "",
    question_11: "",
    question_12: "",
    question_13: "",
    question_14: "",
    question_15: "",
    question_16: "",
    question_17: "",
    question_18: "",
    question_19: "",
    question_20: "",
    question_21: "",
    question_22: "",
    question_23: "",
    question_24: "",
    question_25: "",
    question_26: "",
    question_27: "",
    question_28: "",
    question_29: "",
    question_30: "",
    question_31: "",
    question_32: "",
    question_33: "",
    question_34: "",
    question_35: "question_35",
    question_36: "question_36",
    question_37: "question_37",
    question_38: "question_38",
    question_39: "question_39",
    question_40: "question_40",
    question_41: "question_41",
    question_42: "question_42",
    question_43: "question_43",
    question_44: "question_44",
    question_45: "question_45",
    question_46: "question_46",
    question_47: "question_47",
    question_48: "question_48",
    question_49: "question_49",
    question_50: "",
    question_51: "",
    question_52: "",
    question_53: "",
    question_54: "",
    question_55: "",
    question_56: "",
    question_57: "",
    question_58: "",
    answers_complete: 0,
  };

  console.log("UploadFourth35To49 - RESPONSE:");
  AxiosCall(url, data);
}

function UploadFifth50To57(input) {
  let url = "http://localhost:3001/update";
  let data = {
    record_id: input.record_id,
    question_1: "",
    question_2: "",
    question_3: "",
    question_4: "",
    question_5: "",
    question_6: "",
    question_7: "",
    question_8: "",
    question_9: "",
    question_10: "",
    question_11: "",
    question_12: "",
    question_13: "",
    question_14: "",
    question_15: "",
    question_16: "",
    question_17: "",
    question_18: "",
    question_19: "",
    question_20: "",
    question_21: "",
    question_22: "",
    question_23: "",
    question_24: "",
    question_25: "",
    question_26: "",
    question_27: "",
    question_28: "",
    question_29: "",
    question_30: "",
    question_31: "",
    question_32: "",
    question_33: "",
    question_34: "",
    question_35: "",
    question_36: "",
    question_37: "",
    question_38: "",
    question_39: "",
    question_40: "",
    question_41: "",
    question_42: "",
    question_43: "",
    question_44: "",
    question_45: "",
    question_46: "",
    question_47: "",
    question_48: "",
    question_49: "",
    question_50: "question_50",
    question_51: "question_51",
    question_52: "question_52",
    question_53: "question_53",
    question_54: "question_54",
    question_55: "question_55",
    question_56: "question_56",
    question_57: "question_57",
    question_58: "",
    answers_complete: 0,
  };

  console.log("UploadFifth50To57 - RESPONSE:");
  AxiosCall(url, data);
}

function UploadSixth58(input) {
  let url = "http://localhost:3001/update";
  let data = {
    record_id: input.record_id,
    question_1: "",
    question_2: "",
    question_3: "",
    question_4: "",
    question_5: "",
    question_6: "",
    question_7: "",
    question_8: "",
    question_9: "",
    question_10: "",
    question_11: "",
    question_12: "",
    question_13: "",
    question_14: "",
    question_15: "",
    question_16: "",
    question_17: "",
    question_18: "",
    question_19: "",
    question_20: "",
    question_21: "",
    question_22: "",
    question_23: "",
    question_24: "",
    question_25: "",
    question_26: "",
    question_27: "",
    question_28: "",
    question_29: "",
    question_30: "",
    question_31: "",
    question_32: "",
    question_33: "",
    question_34: "",
    question_35: "",
    question_36: "",
    question_37: "",
    question_38: "",
    question_39: "",
    question_40: "",
    question_41: "",
    question_42: "",
    question_43: "",
    question_44: "",
    question_45: "",
    question_46: "",
    question_47: "",
    question_48: "",
    question_49: "",
    question_50: "",
    question_51: "",
    question_52: "",
    question_53: "",
    question_54: "",
    question_55: "",
    question_56: "",
    question_57: "",
    question_58: "question_58",
    answers_complete: 2,
  };

  console.log("UploadSixth58 - RESPONSE:");
  AxiosCall(url, data);
}

function AxiosCall(url, data) {
  axios
    .post(url, data)
    .then(function (response) {
      // TODO: Save record_id
      console.log(response.data.responseData);
    })
    .catch(function (error) {
      // TODO: Alert user
      console.log(error.data.errorData);
    });
}

export {
  UploadFirst1To7,
  UploadSecond8To26,
  UploadThird27To34,
  UploadFourth35To49,
  UploadFifth50To57,
  UploadSixth58,
};
